# airports.py
# All airport data — add or edit airports here.
# Each entry: name, city, country, terminals, airlines, destinations

AIRPORTS = {
    "SIN": {
        "name": "Changi Airport",
        "city": "Singapore",
        "country": "Singapore",
        "terminals": ["T1", "T2", "T3", "T4"],
        "airlines": ["Singapore Airlines", "Scoot", "Jetstar Asia", "Qatar Airways", "Emirates",
                     "Cathay Pacific", "Malaysia Airlines", "Garuda Indonesia", "Qantas", "Air India"],
        "destinations": ["London", "Sydney", "Tokyo", "Dubai", "Hong Kong", "Bangkok",
                         "Kuala Lumpur", "Jakarta", "Mumbai", "Seoul", "Amsterdam", "Paris",
                         "Melbourne", "Taipei", "Frankfurt", "Colombo", "Manila", "Osaka"],
    },
    "LHR": {
        "name": "Heathrow Airport",
        "city": "London",
        "country": "United Kingdom",
        "terminals": ["T2", "T3", "T4", "T5"],
        "airlines": ["British Airways", "Virgin Atlantic", "Lufthansa", "Air France", "Emirates",
                     "United Airlines", "American Airlines", "Cathay Pacific", "Singapore Airlines", "Qantas"],
        "destinations": ["New York", "Dubai", "Los Angeles", "Singapore", "Sydney", "Frankfurt",
                         "Paris", "Amsterdam", "Hong Kong", "Toronto", "Tokyo", "Mumbai",
                         "Cape Town", "Doha", "Chicago", "Miami", "Dublin"],
    },
    "JFK": {
        "name": "John F. Kennedy International",
        "city": "New York",
        "country": "United States",
        "terminals": ["T1", "T2", "T4", "T5", "T8"],
        "airlines": ["American Airlines", "Delta Air Lines", "JetBlue", "British Airways",
                     "Lufthansa", "Air France", "Emirates", "Cathay Pacific", "Korean Air", "Singapore Airlines"],
        "destinations": ["London", "Los Angeles", "Miami", "Chicago", "San Francisco", "Paris",
                         "Frankfurt", "Dubai", "Hong Kong", "Tokyo", "Toronto", "Cancun",
                         "Rome", "Amsterdam", "Zurich", "Madrid", "Dublin"],
    },
    "DXB": {
        "name": "Dubai International Airport",
        "city": "Dubai",
        "country": "United Arab Emirates",
        "terminals": ["T1", "T2", "T3"],
        "airlines": ["Emirates", "flydubai", "Air Arabia", "Etihad Airways", "Qatar Airways",
                     "British Airways", "Lufthansa", "Air India", "Philippine Airlines", "Singapore Airlines"],
        "destinations": ["London", "Mumbai", "Karachi", "Lahore", "Manila", "Singapore", "Bangkok",
                         "Frankfurt", "Paris", "New York", "Nairobi", "Lagos", "Cairo",
                         "Colombo", "Islamabad", "Dhaka", "Kathmandu", "Amman"],
    },
    "HND": {
        "name": "Haneda Airport",
        "city": "Tokyo",
        "country": "Japan",
        "terminals": ["T1", "T2", "T3"],
        "airlines": ["Japan Airlines", "ANA", "Air Do", "Skymark", "Peach Aviation",
                     "Korean Air", "Cathay Pacific", "Delta Air Lines", "United Airlines", "Singapore Airlines"],
        "destinations": ["Seoul", "Beijing", "Shanghai", "Hong Kong", "Singapore", "Sydney",
                         "Los Angeles", "New York", "London", "Frankfurt", "Bangkok",
                         "Taipei", "Sapporo", "Osaka", "Fukuoka", "Kuala Lumpur"],
    },
    "SYD": {
        "name": "Kingsford Smith Airport",
        "city": "Sydney",
        "country": "Australia",
        "terminals": ["T1", "T2", "T3"],
        "airlines": ["Qantas", "Virgin Australia", "Jetstar", "Singapore Airlines", "Emirates",
                     "Cathay Pacific", "Air New Zealand", "United Airlines", "American Airlines", "Malaysia Airlines"],
        "destinations": ["Melbourne", "Brisbane", "Auckland", "Singapore", "Dubai", "Los Angeles",
                         "Tokyo", "Hong Kong", "London", "Bali", "Bangkok", "Kuala Lumpur",
                         "Fiji", "Delhi", "Doha", "Perth", "Adelaide"],
    },
    "CDG": {
        "name": "Charles de Gaulle Airport",
        "city": "Paris",
        "country": "France",
        "terminals": ["T1", "T2E", "T2F", "T3"],
        "airlines": ["Air France", "Transavia", "easyJet", "Lufthansa", "British Airways",
                     "Delta Air Lines", "Emirates", "Turkish Airlines", "Finnair", "Iberia"],
        "destinations": ["London", "New York", "Dubai", "Montreal", "Casablanca", "Tokyo",
                         "Singapore", "Barcelona", "Rome", "Amsterdam", "Chicago",
                         "Los Angeles", "Tunis", "Dakar", "Algiers", "Athens", "Lisbon"],
    },
    "FRA": {
        "name": "Frankfurt Airport",
        "city": "Frankfurt",
        "country": "Germany",
        "terminals": ["T1", "T2"],
        "airlines": ["Lufthansa", "Condor", "Ryanair", "Turkish Airlines", "Air France",
                     "British Airways", "Emirates", "United Airlines", "Singapore Airlines", "Cathay Pacific"],
        "destinations": ["Munich", "London", "Dubai", "New York", "Singapore", "Hong Kong",
                         "Bangkok", "Istanbul", "Madrid", "Rome", "Toronto", "Tokyo",
                         "Zurich", "Vienna", "Amsterdam", "Cairo", "Nairobi"],
    },
    "BKK": {
        "name": "Suvarnabhumi Airport",
        "city": "Bangkok",
        "country": "Thailand",
        "terminals": ["Main", "Satellite"],
        "airlines": ["Thai Airways", "Bangkok Airways", "AirAsia", "Nok Air", "Scoot",
                     "Singapore Airlines", "Cathay Pacific", "Qatar Airways", "Emirates", "Korean Air"],
        "destinations": ["Singapore", "Hong Kong", "Tokyo", "Seoul", "Kuala Lumpur", "Chiang Mai",
                         "Phuket", "Doha", "Dubai", "London", "Frankfurt", "Sydney",
                         "Beijing", "Colombo", "Mumbai", "Osaka", "Taipei"],
    },
    "HKG": {
        "name": "Hong Kong International Airport",
        "city": "Hong Kong",
        "country": "China SAR",
        "terminals": ["T1", "T2"],
        "airlines": ["Cathay Pacific", "HK Express", "Greater Bay Airlines", "Singapore Airlines",
                     "Japan Airlines", "ANA", "Emirates", "Qantas", "British Airways", "Air China"],
        "destinations": ["Singapore", "Tokyo", "London", "Sydney", "Dubai", "Bangkok", "Seoul",
                         "Taipei", "Shanghai", "Beijing", "Kuala Lumpur", "Manila",
                         "Los Angeles", "Vancouver", "Frankfurt", "Mumbai", "Melbourne"],
    },
    "MAA": {
        "name": "Chennai International Airport",
        "city": "Chennai",
        "country": "India",
        "terminals": ["T1", "T2", "T4"],
        "airlines": ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst", "Emirates",
                     "Singapore Airlines", "Sri Lankan Airlines", "Malaysia Airlines", "Qatar Airways",
                     "Oman Air", "Air Arabia"],
        "destinations": ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Kolkata", "Dubai",
                         "Singapore", "Kuala Lumpur", "Colombo", "Doha", "Abu Dhabi",
                         "Muscat", "London", "Bangkok", "Male", "Sharjah", "Bahrain", "Kuwait"],
    },
    "BOM": {
        "name": "Chhatrapati Shivaji Maharaj International",
        "city": "Mumbai",
        "country": "India",
        "terminals": ["T1", "T2"],
        "airlines": ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst", "Emirates",
                     "Etihad Airways", "Qatar Airways", "British Airways", "Lufthansa", "Singapore Airlines"],
        "destinations": ["Delhi", "Bengaluru", "Hyderabad", "Chennai", "Kolkata", "Dubai",
                         "London", "New York", "Singapore", "Doha", "Abu Dhabi",
                         "Toronto", "Frankfurt", "Bangkok", "Nairobi", "Mauritius", "Sydney"],
    },
    "DEL": {
        "name": "Indira Gandhi International Airport",
        "city": "New Delhi",
        "country": "India",
        "terminals": ["T1", "T2", "T3"],
        "airlines": ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst", "Emirates",
                     "Qatar Airways", "British Airways", "Lufthansa", "Singapore Airlines", "United Airlines"],
        "destinations": ["Mumbai", "Bengaluru", "Hyderabad", "Chennai", "Kolkata", "Dubai",
                         "London", "New York", "Singapore", "Doha", "Frankfurt",
                         "Toronto", "Bangkok", "Sydney", "Tokyo", "Paris", "Amsterdam"],
    },
    "BLR": {
        "name": "Kempegowda International Airport",
        "city": "Bengaluru",
        "country": "India",
        "terminals": ["T1", "T2"],
        "airlines": ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst", "Emirates",
                     "Singapore Airlines", "Qatar Airways", "Oman Air", "Etihad Airways",
                     "Malaysia Airlines", "Scoot"],
        "destinations": ["Mumbai", "Delhi", "Hyderabad", "Chennai", "Kolkata", "Dubai",
                         "Singapore", "Doha", "Muscat", "Abu Dhabi", "Bangkok",
                         "Kuala Lumpur", "London", "Frankfurt", "Male", "Sharjah"],
    },
    "HYD": {
        "name": "Rajiv Gandhi International Airport",
        "city": "Hyderabad",
        "country": "India",
        "terminals": ["T1"],
        "airlines": ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst", "Emirates",
                     "Qatar Airways", "Oman Air", "Air Arabia", "flydubai",
                     "Singapore Airlines", "Etihad Airways"],
        "destinations": ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Kolkata", "Dubai",
                         "Singapore", "Doha", "Muscat", "Abu Dhabi", "Sharjah",
                         "Kuwait", "Bahrain", "London", "Bangkok", "Male"],
    },
    "KUL": {
        "name": "Kuala Lumpur International Airport",
        "city": "Kuala Lumpur",
        "country": "Malaysia",
        "terminals": ["T1", "T2", "KLIA2"],
        "airlines": ["Malaysia Airlines", "AirAsia", "Batik Air", "Firefly", "Singapore Airlines",
                     "Emirates", "Qatar Airways", "Cathay Pacific", "Thai Airways", "Korean Air"],
        "destinations": ["Singapore", "Bangkok", "Jakarta", "Hong Kong", "Tokyo", "Dubai",
                         "London", "Sydney", "Melbourne", "Doha", "Colombo", "Dhaka",
                         "Manila", "Seoul", "Taipei", "Osaka", "Karachi"],
    },
    "ICN": {
        "name": "Incheon International Airport",
        "city": "Seoul",
        "country": "South Korea",
        "terminals": ["T1", "T2"],
        "airlines": ["Korean Air", "Asiana Airlines", "Jin Air", "Jeju Air", "Singapore Airlines",
                     "Japan Airlines", "Cathay Pacific", "Delta Air Lines", "United Airlines", "Lufthansa"],
        "destinations": ["Tokyo", "Beijing", "Shanghai", "Hong Kong", "Singapore", "Bangkok",
                         "Osaka", "Taipei", "New York", "Los Angeles", "London",
                         "Frankfurt", "Sydney", "Vancouver", "Kuala Lumpur", "Manila"],
    },
    "IST": {
        "name": "Istanbul Airport",
        "city": "Istanbul",
        "country": "Turkey",
        "terminals": ["T1"],
        "airlines": ["Turkish Airlines", "Pegasus Airlines", "SunExpress", "Lufthansa",
                     "British Airways", "Air France", "Emirates", "Qatar Airways",
                     "Royal Jordanian", "Aeroflot"],
        "destinations": ["London", "Frankfurt", "Dubai", "Doha", "New York", "Paris",
                         "Amsterdam", "Moscow", "Cairo", "Riyadh", "Jeddah",
                         "Athens", "Rome", "Madrid", "Bangkok", "Singapore"],
    },
    "DOH": {
        "name": "Hamad International Airport",
        "city": "Doha",
        "country": "Qatar",
        "terminals": ["T1"],
        "airlines": ["Qatar Airways", "flydubai", "Air Arabia", "IndiGo", "Air India",
                     "British Airways", "Lufthansa", "American Airlines", "Cathay Pacific", "Singapore Airlines"],
        "destinations": ["London", "New York", "Dubai", "Mumbai", "Delhi", "Bangkok",
                         "Singapore", "Nairobi", "Lagos", "Johannesburg", "Frankfurt",
                         "Paris", "Tokyo", "Sydney", "Kuala Lumpur", "Colombo"],
    },
    "LAX": {
        "name": "Los Angeles International Airport",
        "city": "Los Angeles",
        "country": "United States",
        "terminals": ["T1", "T2", "T3", "T4", "T5", "T6", "T7", "B"],
        "airlines": ["American Airlines", "Delta Air Lines", "United Airlines", "Southwest",
                     "Alaska Airlines", "Japan Airlines", "ANA", "Cathay Pacific",
                     "Korean Air", "British Airways", "Qantas"],
        "destinations": ["New York", "San Francisco", "Seattle", "Chicago", "Honolulu",
                         "Tokyo", "Seoul", "Sydney", "London", "Vancouver", "Toronto",
                         "Mexico City", "Auckland", "Shanghai", "Hong Kong", "Singapore"],
    },
    "AMS": {
        "name": "Amsterdam Airport Schiphol",
        "city": "Amsterdam",
        "country": "Netherlands",
        "terminals": ["T1"],
        "airlines": ["KLM", "Transavia", "easyJet", "Ryanair", "Lufthansa", "British Airways",
                     "Air France", "Delta Air Lines", "United Airlines", "Singapore Airlines"],
        "destinations": ["London", "New York", "Paris", "Frankfurt", "Dubai", "Singapore",
                         "Tokyo", "Kuala Lumpur", "Bangkok", "Toronto", "Los Angeles",
                         "Cape Town", "Nairobi", "Accra", "Lagos", "Bogota"],
    },
    "CGK": {
        "name": "Soekarno-Hatta International Airport",
        "city": "Jakarta",
        "country": "Indonesia",
        "terminals": ["T1", "T2", "T3"],
        "airlines": ["Garuda Indonesia", "Lion Air", "Batik Air", "Citilink", "AirAsia",
                     "Singapore Airlines", "Malaysia Airlines", "Cathay Pacific", "Emirates", "Qatar Airways"],
        "destinations": ["Singapore", "Kuala Lumpur", "Bangkok", "Hong Kong", "Tokyo",
                         "Seoul", "Dubai", "Melbourne", "Sydney", "Doha",
                         "Taipei", "Guangzhou", "Shanghai", "Beijing", "Amsterdam"],
    },
    "MNL": {
        "name": "Ninoy Aquino International Airport",
        "city": "Manila",
        "country": "Philippines",
        "terminals": ["T1", "T2", "T3", "T4"],
        "airlines": ["Philippine Airlines", "Cebu Pacific", "AirAsia Philippines", "Singapore Airlines",
                     "Cathay Pacific", "Emirates", "Qatar Airways", "Korean Air",
                     "Japan Airlines", "China Southern"],
        "destinations": ["Singapore", "Hong Kong", "Tokyo", "Seoul", "Kuala Lumpur",
                         "Dubai", "Doha", "Taipei", "Bangkok", "Osaka",
                         "Riyadh", "Jeddah", "Sydney", "London", "Los Angeles"],
    },
    "CAI": {
        "name": "Cairo International Airport",
        "city": "Cairo",
        "country": "Egypt",
        "terminals": ["T1", "T2", "T3"],
        "airlines": ["EgyptAir", "Nile Air", "Air Arabia Egypt", "Emirates", "flydubai",
                     "Qatar Airways", "Turkish Airlines", "Lufthansa", "British Airways",
                     "Saudi Arabian Airlines"],
        "destinations": ["Dubai", "Riyadh", "Jeddah", "Doha", "London", "Frankfurt",
                         "Paris", "Rome", "Athens", "Istanbul", "Amman",
                         "Beirut", "New York", "Bangkok", "Casablanca", "Nairobi"],
    },
    "JNB": {
        "name": "O.R. Tambo International Airport",
        "city": "Johannesburg",
        "country": "South Africa",
        "terminals": ["T1"],
        "airlines": ["South African Airways", "Comair", "FlySafair", "Airlink", "Emirates",
                     "Qatar Airways", "British Airways", "Lufthansa", "Ethiopian Airlines", "Kenya Airways"],
        "destinations": ["Cape Town", "Durban", "London", "Dubai", "Doha", "Frankfurt",
                         "Amsterdam", "Nairobi", "Lagos", "Accra", "Addis Ababa",
                         "Luanda", "Mauritius", "New York", "Hong Kong", "Sydney"],
    },
}
